// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfrscnwepirretbimqjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmcnNjbndlcGlycmV0YmltcWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2Njc5NDcsImV4cCI6MjA2MTI0Mzk0N30.hibzj4jRbmAlzNHkKnaUIQRUDnnTPMJGLXjClBEPUkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);